name: Sync Shopify to Notion

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:
    inputs:
      use_graphql:
        description: 'Use GraphQL sync (recommended)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run sync (GraphQL)
      if: github.event.inputs.use_graphql != 'false'
      env:
        SHOPIFY_STORE_NAME: ${{ secrets.SHOPIFY_STORE_NAME }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      run: |
        echo "🚀 Running GraphQL sync (recommended)..."
        npm run sync
    
    - name: Run sync (REST Legacy)
      if: github.event.inputs.use_graphql == 'false'
      env:
        SHOPIFY_STORE_NAME: ${{ secrets.SHOPIFY_STORE_NAME }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      run: |
        echo "⚠️ Running REST sync (legacy)..."
        npm run sync-legacy
    
    - name: Sync status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Sync completed successfully!"
        else
          echo "❌ Sync failed. Check the logs above."
        fi
